"""HTML report — single self-contained page (inline CSS, Jinja2)."""

from __future__ import annotations

from pathlib import Path

from jinja2 import DictLoader, Environment, select_autoescape

from wikibench.models.result import BenchmarkResult

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>WikiBench — {{ result.run_id }}</title>
  <style>
    :root { --bg: #0d1117; --card: #161b22; --border: #30363d; --text: #e6edf3; --muted: #8b949e; --accent: #58a6ff; --good: #3fb950; --warn: #d29922; }
    body { font-family: ui-sans-serif, system-ui, sans-serif; background: var(--bg); color: var(--text); margin: 0; padding: 1.5rem; line-height: 1.5; }
    h1 { font-size: 1.35rem; margin: 0 0 0.5rem; }
    h2 { font-size: 1.1rem; margin: 1.5rem 0 0.75rem; border-bottom: 1px solid var(--border); padding-bottom: 0.35rem; }
    .meta { color: var(--muted); font-size: 0.9rem; margin-bottom: 1rem; }
    table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
    th, td { border: 1px solid var(--border); padding: 0.45rem 0.65rem; text-align: left; }
    th { background: var(--card); color: var(--muted); font-weight: 600; }
    tr:nth-child(even) { background: rgba(255,255,255,0.02); }
    .score-good { color: var(--good); font-weight: 600; }
    .score-mid { color: var(--warn); }
    .score-low { color: #f85149; }
    .panel { background: var(--card); border: 1px solid var(--border); border-radius: 6px; padding: 1rem; margin-top: 0.75rem; }
    .warn { color: var(--warn); }
    footer { margin-top: 2rem; font-size: 0.8rem; color: var(--muted); }
  </style>
</head>
<body>
  <h1>WikiBench Report</h1>
  <p class="meta">
    Run ID: <code>{{ result.run_id }}</code> &middot;
    {{ result.created_at.strftime("%Y-%m-%d %H:%M:%S UTC") }} &middot;
    Impl: <strong>{{ result.impl }}</strong> &middot;
    Corpus: <code>{{ result.corpus_id }}</code>
  </p>

  <h2>Environment</h2>
  <div class="panel">
    <table>
      <tr><th>Field</th><th>Value</th></tr>
      <tr><td>WikiBench</td><td>{{ result.environment.wikibench_version }}</td></tr>
      <tr><td>Python</td><td>{{ result.environment.python_version.split()[0] }}</td></tr>
      <tr><td>OS</td><td>{{ result.environment.os }}</td></tr>
      <tr><td>Seed</td><td>{{ result.environment.seed }}</td></tr>
      {% for role, model in result.environment.llm_models.items() %}
      <tr><td>LLM ({{ role }})</td><td><code>{{ model }}</code></td></tr>
      {% endfor %}
    </table>
  </div>

  <h2>Ingest</h2>
  <div class="panel">
    <table>
      <tr><th>Metric</th><th>Value</th></tr>
      <tr><td>Wiki tokens</td><td>{{ result.ingest.wiki_tokens }}</td></tr>
      <tr><td>Tokens in / out</td><td>{{ result.ingest.tokens_in }} / {{ result.ingest.tokens_out }}</td></tr>
      <tr><td>LLM calls</td><td>{{ result.ingest.llm_calls }}</td></tr>
      <tr><td>Duration</td><td>{{ "%.2f"|format(result.ingest.duration_s) }}s</td></tr>
      {% if result.ingest.cost_usd is not none %}
      <tr><td>Cost (USD)</td><td>{{ "%.6f"|format(result.ingest.cost_usd) }}</td></tr>
      {% endif %}
    </table>
  </div>

  <h2>Per-task</h2>
  {% for task_id, tr in result.per_task.items() %}
  <h3 style="font-size:1rem;margin:1rem 0 0.5rem;">{{ task_id }} <span class="meta">v{{ tr.task_version }}</span></h3>
  <div class="panel">
    <table>
      <tr><th>Slice</th><th>Value</th></tr>
      {% for key, val in tr.slices.items() %}
      <tr>
        <td>{{ key }}</td>
        <td>
          {% if val is number %}
            <span class="{% if val >= 0.8 %}score-good{% elif val >= 0.5 %}score-mid{% else %}score-low{% endif %}">{{ "%.4f"|format(val) }}</span>
          {% else %}
            {{ val }}
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </table>
    {% if tr.warnings %}
    <p class="warn">{% for w in tr.warnings %} {{ w }}{% endfor %}</p>
    {% endif %}
  </div>
  {% endfor %}

  <h2>Flat metrics</h2>
  <div class="panel">
    <table>
      <tr><th>Metric</th><th>Score</th></tr>
      {% for key in result.metrics|sort %}
      {% set v = result.metrics[key] %}
      <tr>
        <td><code>{{ key }}</code></td>
        <td><span class="{% if v >= 0.8 %}score-good{% elif v >= 0.5 %}score-mid{% else %}score-low{% endif %}">{{ "%.4f"|format(v) }}</span></td>
      </tr>
      {% endfor %}
    </table>
  </div>

  {% if result.warnings %}
  <h2>Warnings</h2>
  <div class="panel warn">
    <ul>{% for w in result.warnings %}<li>{{ w }}</li>{% endfor %}</ul>
  </div>
  {% endif %}

  <footer>Generated by WikiBench · HTML report (Phase 1 Week 6)</footer>
</body>
</html>
"""


def render(result: BenchmarkResult) -> str:
    """Return a complete HTML document string."""
    env = Environment(
        loader=DictLoader({"report.html": _TEMPLATE}),
        autoescape=select_autoescape(["html", "xml"]),
    )
    tpl = env.get_template("report.html")
    return tpl.render(result=result)


def save(result: BenchmarkResult, path: str | Path) -> Path:
    """Write HTML to *path* (creates parent dirs)."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render(result), encoding="utf-8")
    return p.resolve()
